// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrcKy7TfQJPTGXfa6XX-Ju1Mehz_4Z3qU',
    appId: '1:983736376346:web:bc1470a4cd98bc048285a3',
    messagingSenderId: '983736376346',
    projectId: 'flutter-ecommerce-4beda',
    authDomain: 'flutter-ecommerce-4beda.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-4beda.firebasestorage.app',
    measurementId: 'G-Q7G7CW7TDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0c8GLKq0k1GC170lB0iXK1l0LBoSc4a8',
    appId: '1:983736376346:android:b94c09e1249ff34d8285a3',
    messagingSenderId: '983736376346',
    projectId: 'flutter-ecommerce-4beda',
    storageBucket: 'flutter-ecommerce-4beda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB57VLTxBNfkzJXDOBpF1L_gDgVElSruiY',
    appId: '1:983736376346:ios:0112d6a314b71b118285a3',
    messagingSenderId: '983736376346',
    projectId: 'flutter-ecommerce-4beda',
    storageBucket: 'flutter-ecommerce-4beda.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB57VLTxBNfkzJXDOBpF1L_gDgVElSruiY',
    appId: '1:983736376346:ios:0112d6a314b71b118285a3',
    messagingSenderId: '983736376346',
    projectId: 'flutter-ecommerce-4beda',
    storageBucket: 'flutter-ecommerce-4beda.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrcKy7TfQJPTGXfa6XX-Ju1Mehz_4Z3qU',
    appId: '1:983736376346:web:aeb3e07c93a308798285a3',
    messagingSenderId: '983736376346',
    projectId: 'flutter-ecommerce-4beda',
    authDomain: 'flutter-ecommerce-4beda.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-4beda.firebasestorage.app',
    measurementId: 'G-X389STMKP2',
  );
}
